#version: '3.8'

services:
  # PostgresQL Database
  postgres:
    image: postgres:15
    container_name: analytics_db
    environment:
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analytics123
      POSTGRES_DB: analytics_data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - analytics-network
    restart: unless-stopped

# Jupyter Notebook for Analysis

  jupiter:
    image: jupyter/scipy-notebook:latest
    container_name: analytics-jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "80:8888"
    networks:
      - analytics-network
    restart: unless-stopped
    depends_on:
      - postgres

# Adminer - Database WEB UI

  adminer:
    image: adminer:latest
    container_name: analytics_adminer
    ports:
      - "8080:8080"
    networks:
      - analytics-network
    restart: unless-stopped
    depends_on:
      - postgres

# ETL Service
  etl:
    build: ./etl
    container_name: analytics_etl
    volumes:
      - ./etl/sample_data.csv:/data/sample_data.csv
    networks:
      - analytics-network
    depends_on:
      - postgres

networks:
  analytics-network:
    driver: bridge
